return {
    { "catppuccin", enabled = false },
    { "dashboard-nvim", enabled = false },
    { "flash.nvim", enabled = false },
    { "indent-blankline.nvim", enabled = false },
    { "mini.ai", enabled = false },
    { "mini.indentscope", enabled = false },
    { "neo-tree.nvim", enabled = false },
    { "noice.nvim", enabled = false },
    { "nvim-notify", enabled = false },
    { "todo-comments.nvim", enabled = false },
    { "vim-illuminate", enabled = false },
    { "mini.surround", enabled = false },
    { "mini.bufremove", enabled = false },
    { "nvim-spectre", enabled = false },
    { "vim-startuptime", enabled = false },
    { "which-key.nvim", enabled = false },
}
